Full Focus: Кампании, Аудитории, Обзор
VK-BMSTU-QA/homework-3-autumn-2024 pull request #4
Opened 2024-11-12 15:42 UTC by Olegsandrik

2024-11-18 00:08 UTC, BeeHeather requested changes
Привет! Хорошая работа, оставила несколько комментариев, посмотри пожалуйста

2024-11-18 00:08 UTC, BeeHeather commented on Full_Focus-Alex-Nikitin.md
> +* При нажатии на соответствующий кейс аудитория фильтруется по нему:
Тут тоже либо убери список, либо покомпактнее сделай

2024-11-18 00:08 UTC, BeeHeather commented on Full_Focus-Alex-Nikitin.md
> +* При нажатии "Отменить" фильтрация отменяется
Вообще, я бы не делала тесты на фильтрацию в каждом разделе (по сути это один и тот же модуль). Давай его просто отдельно вынесем, получается будут Кампании, Аудитории, Обзор и Фильтрация (на примере кампании например)

2024-11-18 00:08 UTC, BeeHeather commented on Full_Focus-Alex-Nikitin.md
> +* При нажатии на Полезные материалы открывается новая вкладка с информацией
Тут можно указать ссылку страницы, на которую происходит редирект

2024-11-18 00:08 UTC, BeeHeather commented on Full_Focus-Alex-Nikitin.md
> +* При вводе менее 600 рублей выводится ошибка
А есть максимальное значение?

2024-11-18 11:07 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +* При нажатии на кнопку "Объявления" отображается соответствующая вкладка
Тот, просто так отображается. Там сверху выделено "Объявления"
У меня просто их нет в аккаунте

2024-11-18 11:14 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +* При вводе менее 600 рублей выводится ошибка
Добавил

2024-11-18 11:14 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +* При нажатии на Полезные материалы открывается новая вкладка с информацией
Добавил ссылку

2024-11-18 11:15 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +* При нажатии "Отменить" фильтрация отменяется
То есть просто убрать эти модули у Аудитории, Обзоров?

2024-11-18 11:15 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +* При нажатии на соответствующий кейс аудитория фильтруется по нему:
Сделал

2024-11-18 11:15 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +* При попытке ввода значения менее 100 выводится ошибка
Добавил

2024-11-18 11:15 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +Сегодня
Сделал компактнее

2024-11-18 11:15 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +* Указать дату можно при нажатии на нее, но невозможно установить на позапрошлый год и ранее, а так же на год вперед
Раскинул на 3

2024-11-18 11:15 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +* При попытке повторного сохранения фильтра с тем же названием выводится ошибка (с другим именем нет ошибки)
Добавил ограничения

2024-11-18 11:16 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +Мобильное приложение
Сделал его компактным

2024-11-18 11:16 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +При нажатии соответствующей кнопки выбирается объект рекламы:
Сделал

2024-11-18 11:16 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +* Во вкладке "Статус" доступна фильтрация при нажатии соответсвующих кнопок
Поправил

2024-11-18 11:16 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +* При выборе каких-то пунктов настройки можно сбросить все, нажав на соответствующую кнопку
Добавил названия элементов

2024-11-18 12:10 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +* При нажатии "Отменить" фильтрация отменяется
Убрал в Аудитории, но в Обзоре описан функционал именно нажатия на кнопку, которая перекидывает на вкладку с фильтрами. Поэтому его оставил

2024-11-20 21:21 UTC, BeeHeather requested changes
Привет! Оставила пару небольших комментов, посмотри пожалуйста

2024-11-20 21:21 UTC, BeeHeather commented on Full_Focus-Alex-Nikitin.md
> +* При выборе каких-то пунктов настройки можно сбросить все, нажав на кнопку нажав на кнопку "Сбросить все"
Вот тут еще стоит переформулировать слово "каких-то", нужна конкретика

2024-11-20 21:21 UTC, BeeHeather commented on Full_Focus-Alex-Nikitin.md
> +При нажатии кнопки "Мобильное приложение", "Сообщество ВКонтакте", "Сайт", "Баннерная реклама", "Видеореклама", "Запись, видео или клип", "Реклама в Дзене", "HTML5 баннер" , "Премиальное размещение",
Может попробуем здесь не указывать весь список, а обобщить его как нибудь? в любом случае это уже есть на скрине

2024-11-21 12:31 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +* При выборе каких-то пунктов настройки можно сбросить все, нажав на кнопку нажав на кнопку "Сбросить все"
сделал

2024-11-21 12:31 UTC, Olegsandrik commented on Full_Focus-Alex-Nikitin.md
> +При нажатии кнопки "Мобильное приложение", "Сообщество ВКонтакте", "Сайт", "Баннерная реклама", "Видеореклама", "Запись, видео или клип", "Реклама в Дзене", "HTML5 баннер" , "Премиальное размещение",
заменил на объекты рекламы

2024-11-25 14:40 UTC, BeeHeather approved these changes
Аппрув

2025-02-02 22:40 UTC, closed without merging